#operator prod
prod:
    args:
        input:
            dtype: tensor
        dim:
            dtype: int
            default: None
        keepdim:
            dtype: bool
            default: False
        dtype:
            dtype: TypeId
            arg_handler: dtype_to_type_id
            default: None
    returns:
        output:
            dtype: tensor
