#operator prod_ext
prod_ext:
    args:
        input:
            dtype: tensor
        dim:
            dtype: int
            default: None
        keepdim:
            dtype: bool
            default: False
        dtype:
            dtype: TypeId
            arg_handler: dtype_to_type_id
            default: None
    returns:
        output:
            dtype: tensor
    dispatch:
        enable: True
        Ascend: ProdExtAscend
        CPU: ProdExtCPU
        GPU: ProdExtGPU
