# Copyright 2020 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""ut for model serialize(save/load)"""
import os
from io import BytesIO
import stat
import numpy as np
import pytest
import onnxruntime as ort

import mindspore as ms
from mindspore import ops
import mindspore.nn as nn
from mindspore import context
from mindspore.common.parameter import Parameter
from mindspore.common.tensor import Tensor
from mindspore.ops import operations as P
from mindspore.train.serialization import export

context.set_context(mode=context.GRAPH_MODE)


def is_enable_onnxruntime():
    val = os.getenv("ENABLE_ONNXRUNTIME", "False")
    if val in ('ON', 'on', 'TRUE', 'True', 'true'):
        return True
    return False


run_on_onnxruntime = pytest.mark.skipif(not is_enable_onnxruntime(), reason="Only support running on onnxruntime")


def teardown_module():
    cur_dir = os.path.dirname(os.path.realpath(__file__))
    for filename in os.listdir(cur_dir):
        if filename.find('ms_output_') == 0 and filename.find('.pb') > 0:
            # delete temp files generated by run ut
            os.chmod(filename, stat.S_IWRITE)
            os.remove(filename)


class BatchNormTester(nn.Cell):
    """used to test exporting network in training mode in onnx format"""

    def __init__(self, num_features):
        super(BatchNormTester, self).__init__()
        self.bn = nn.BatchNorm2d(num_features)

    def construct(self, x):
        return self.bn(x)


@pytest.mark.skip(reason="No support in dynamic shape.")
def test_batchnorm_train_onnx_export():
    """test onnx export interface does not modify trainable flag of a network"""
    input_ = Tensor(np.ones([1, 3, 32, 32]).astype(np.float32) * 0.01)
    net = BatchNormTester(3)
    net.set_train()
    if not net.training:
        raise ValueError('netowrk is not in training mode')
    onnx_file = 'batch_norm'
    export(net, input_, file_name=onnx_file, file_format='ONNX')

    if not net.training:
        raise ValueError('netowrk is not in training mode')

    file_name = "batch_norm.onnx"
    assert os.path.exists(file_name)
    os.chmod(file_name, stat.S_IWRITE)
    os.remove(file_name)


class LeNet5(nn.Cell):
    """LeNet5 definition"""

    def __init__(self):
        super(LeNet5, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5, pad_mode='valid')
        self.conv2 = nn.Conv2d(6, 16, 5, pad_mode='valid')
        self.fc1 = nn.Dense(16 * 5 * 5, 120)
        self.fc2 = nn.Dense(120, 84)
        self.fc3 = nn.Dense(84, 10)
        self.relu = nn.ReLU()
        self.max_pool2d = nn.MaxPool2d(kernel_size=2, stride=2)
        self.flatten = P.Flatten()

    def construct(self, x):
        x = self.max_pool2d(self.relu(self.conv1(x)))
        x = self.max_pool2d(self.relu(self.conv2(x)))
        x = self.flatten(x)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x


class DefinedNet(nn.Cell):
    """simple Net definition with maxpoolwithargmax."""

    def __init__(self, num_classes=10):
        super(DefinedNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=0, weight_init="zeros")
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU()
        self.maxpool = P.MaxPoolWithArgmax(pad_mode="same", kernel_size=2, strides=2)
        self.flatten = nn.Flatten()
        self.fc = nn.Dense(int(56 * 56 * 64), num_classes)

    def construct(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x, argmax = self.maxpool(x)
        x = self.flatten(x)
        x = self.fc(x)
        return x


class DepthwiseConv2dAndReLU6(nn.Cell):
    """Net for testing DepthwiseConv2d and ReLU6"""
    def __init__(self, input_channel, kernel_size):
        super(DepthwiseConv2dAndReLU6, self).__init__()
        weight_shape = [1, input_channel, kernel_size, kernel_size]
        from mindspore.common.initializer import initializer
        self.weight = Parameter(initializer('ones', weight_shape), name='weight')
        self.depthwise_conv = P.DepthwiseConv2dNative(channel_multiplier=1, kernel_size=(kernel_size, kernel_size))
        self.relu6 = nn.ReLU6()

    def construct(self, x):
        x = self.depthwise_conv(x, self.weight)
        x = self.relu6(x)
        return x


class DeepFMOpNet(nn.Cell):
    """Net definition with Gatherv2 and Tile and Square."""
    def __init__(self):
        super(DeepFMOpNet, self).__init__()
        self.gather = P.Gather()
        self.square = P.Square()
        self.tile = P.Tile()

    def construct(self, x, y):
        x = self.tile(x, (1000, 1))
        x = self.square(x)
        x = self.gather(x, y, 0)
        return x


def gen_tensor(shape, dtype=np.float32):
    return Tensor(np.ones(shape).astype(dtype))


net_cfgs = [
    ('lenet', LeNet5(), gen_tensor([1, 1, 32, 32])),
    # ('maxpoolwithargmax', DefinedNet(), gen_tensor([1, 3, 224, 224])),   # No support in dynamic shape.
    ('depthwiseconv_relu6', DepthwiseConv2dAndReLU6(3, kernel_size=3), gen_tensor([1, 3, 32, 32])),
    ('deepfm_ops', DeepFMOpNet(), (gen_tensor([1, 1]), gen_tensor([1000, 1], dtype=np.int32)))
]


def get_id(cfg):
    _ = cfg
    return list(map(lambda x: x[0], net_cfgs))


# use `pytest test_onnx.py::test_onnx_export[name]` or `pytest test_onnx.py::test_onnx_export -k name` to run single ut
@pytest.mark.parametrize('name, net, inp', net_cfgs, ids=get_id(net_cfgs))
def test_onnx_export(name, net, inp):
    if isinstance(inp, (tuple, list)):
        export(net, *inp, file_name=name, file_format='ONNX')
    else:
        export(net, inp, file_name=name, file_format='ONNX')

    file_file = name + ".onnx"
    assert os.path.exists(file_file)
    os.chmod(file_file, stat.S_IWRITE)
    os.remove(file_file)


@run_on_onnxruntime
@pytest.mark.parametrize('name, net, inp', net_cfgs, ids=get_id(net_cfgs))
def test_onnx_export_load_run(name, net, inp):
    export(net, inp, file_name=name, file_format='ONNX')
    # Load the ONNX model
    model = onnx.load(onnx_file)
    # Check that the IR is well formed
    onnx.checker.check_model(model)
    # Print a human readable representation of the graph
    g = onnx.helper.printable_graph(model.graph)

    ort_session = ort.InferenceSession(onnx_file)
    input_map = {'x': inp.asnumpy()}
    # provide only input x to run model
    outputs = ort_session.run(None, input_map)

    # overwrite default weight to run model
    for item in net.trainable_params():
        default_value = item.data.asnumpy()
        input_map[item.name] = np.ones(default_value.shape, dtype=default_value.dtype)
    outputs = ort_session.run(None, input_map)

    file_name = name + ".onnx"
    assert os.path.exists(file_name)
    os.chmod(file_name, stat.S_IWRITE)
    os.remove(file_name)


class StridedSliceNet(nn.Cell):
    def construct(self, x):
        return P.StridedSlice()(x, (0, 0), (1, 1), (1, 1))


def encrypt_func(model_stream, key):
    plain_data = BytesIO()
    plain_data.write(model_stream)
    return plain_data.getvalue()


def test_export_stridedslice():
    """
    Feature: Export ops.StridedSlice to onnx
    Description: Export ops.StridedSlice to onnx
    Expectation: success
    """
    np_x = np.array([[0, 1], [2, 3]]).astype(np.float32)
    x = Tensor(np_x)
    net = StridedSliceNet()
    export(net, x, file_name='./strided_slice_onnx', file_format='ONNX')
    if os.path.isfile("./strided_slice_onnx.onnx"):
        session = ort.InferenceSession("./strided_slice_onnx.onnx")
        output = session.run(None, {"x": np_x})[0]
        expected = np_x[0:1, 0:1]
        assert np.array_equal(output, expected)
        os.remove("./strided_slice_onnx.onnx")
    else:
        raise RuntimeError(f"Export operator NotEqual to ONNX failed!")


def test_export_lenet_onnx_with_modify_input():
    """
    Feature: Export encrypted LeNet to ONNX
    Description: Export encrypted LeNet to ONNX for modify input/output name
    Expectation: save successfully
    """
    network1 = LeNet5()

    file_name1 = "lenet_modify_input.onnx"
    input_tensor = Tensor(np.ones([32, 1, 32, 32]).astype(np.float32) * 0.01)
    ms.onnx.export(network1, input_tensor, file_name=file_name1, input_names=["input_x"])
    assert os.path.exists(file_name1)
    os.remove(file_name1)

    network2 = LeNet5()
    file_name2 = "lenet_modify_output.onnx"
    input_tensor = Tensor(np.ones([32, 1, 32, 32]).astype(np.float32) * 0.01)
    ms.onnx.export(network2, input_tensor, file_name=file_name2, output_names=["output_x"])
    assert os.path.exists(file_name2)
    os.remove(file_name2)


def test_export_lenet_onnx_with_encryption():
    """
    Feature: Export encrypted LeNet to ONNX
    Description: Test export API to save network with encryption into ONNX
    Expectation: save successfully
    """
    context.set_context(mode=context.GRAPH_MODE, device_target="CPU")
    network = LeNet5()
    network.set_train()
    file_name = "lenet_preprocess.onnx"

    input_tensor = Tensor(np.ones([32, 1, 32, 32]).astype(np.float32) * 0.01)
    ms.export(network, input_tensor, file_name=file_name, file_format='ONNX',
              enc_key=b'123456789', enc_mode=encrypt_func)
    assert os.path.exists(file_name)
    os.remove(file_name)


class Net(nn.Cell):
    def __init__(self):
        super().__init__()
        self.op = ops.NotEqual()

    def construct(self, x, y):
        return self.op(x, y)


def test_export_not_equal():
    """
    Feature: Export ops.NotEqual to onnx
    Description: Export ops.NotEqual to onnx
    Expectation: success
    """
    arr1 = np.array([1, 2, 3]).astype(np.float32)
    arr2 = np.array([1, 0, 3]).astype(np.float32)
    a = Tensor(arr1)
    b = Tensor(arr2)
    net = Net()
    ms.export(net, a, b, file_name='ne', file_format='ONNX')
    if os.path.isfile("./ne.onnx"):
        session = ort.InferenceSession("./ne.onnx")
        output = session.run(None, {"x": arr1, "y": arr2})[0]
        expected = np.array([False, True, False])
        assert np.array_equal(output, expected)
        os.remove("./ne.onnx")
    else:
        raise RuntimeError(f"Export operator NotEqual to ONNX failed!")
