# path variables for metadef submodule, it has to be included after mindspore/core
# and minspore/ccsrc to prevent conflict of op headers

set(METADEF_PATH "${CMAKE_SOURCE_DIR}/metadef")

if(ENABLE_TESTCASES OR ENABLE_D OR ENABLE_ACL)
    message("Note: compile cpp with include file: ${ASCEND_PATH}/latest/include/")
    include_directories(${ASCEND_PATH}/latest/include/)
    include_directories(${ASCEND_PATH}/latest/include/hccl)
    include_directories(${ASCEND_PATH}/latest/include/aoe)
    include_directories(${ASCEND_PATH}/latest/include/exe_graph)
    include_directories(${ASCEND_PATH}/latest/opp/built-in/)
    include_directories(${ASCEND_PATH}/latest/opp/built-in/op_impl/aicpu/aicpu_kernel/inc/)
    include_directories(${ASCEND_PATH}/latest/aarch64-linux/include/)
    include_directories(${ASCEND_PATH}/latest/aarch64-linux/include/experiment)
    include_directories(${ASCEND_PATH}/latest/aarch64-linux/include/experiment/runtime/)
    include_directories(${ASCEND_PATH}/latest/aarch64-linux/include/experiment/msprof/)
    include_directories(${ASCEND_PATH}/latest/x86_64-linux/include/)
    include_directories(${ASCEND_PATH}/latest/x86_64-linux/include/experiment)
    include_directories(${ASCEND_PATH}/latest/x86_64-linux/include/experiment/runtime/)
    include_directories(${ASCEND_PATH}/latest/x86_64-linux/include/experiment/msprof/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/include/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/include/hccl)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/include/aoe)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/include/exe_graph)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/opp/built-in/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/opp/built-in/op_impl/aicpu/aicpu_kernel/inc/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/aarch64-linux/include/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/aarch64-linux/include/experiment)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/aarch64-linux/include/experiment/runtime/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/aarch64-linux/include/experiment/msprof/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/x86_64-linux/include/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/x86_64-linux/include/experiment)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/x86_64-linux/include/experiment/runtime/)
    include_directories(${ASCEND_PATH}/ascend-toolkit/latest/x86_64-linux/include/experiment/msprof/)
    include_directories(${METADEF_PATH}/inc/)
    include_directories(${METADEF_PATH}/inc/external/)
endif()